<a href="https://colab.research.google.com/github/kayla-jackson/spatial-modeling/blob/test-exploratory-sims/notebooks/spatially_correlated_p.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [21]:
# Helper functions to generate a sample from MVN(0, sigma)

def adjacency_matrix(A):
    '''Returns the adjacency matrix W from A, a NumPy array'''
    rows, cols = len(A), len(A[0])
    locs = rows * cols # number of spatial locations on the grid
    W = np.zeros((locs, locs), dtype=int)

    # Iterate through each element in A to determine number of neighbors
    for r in range(rows):
        for c in range(cols):
            for dr, dc in [(-1,0),(1,0),(0,-1),(0,1)]:
                if 0 <= r + dr < rows and 0 <= c + dc < cols:
                    W[r * cols + c][(r + dr) * cols + c + dc] = 1

    return W

def sum_adjacency_matrix(W):
    '''Outputs matrix D with same dimensions as W;
    Sums the number of neighbors of the original points'''
    return np.diag(np.sum(W, axis=1))

def compute_sigma(A, alpha, tau):
    '''Outputs the covariance matrix termed sigma from original matrix A'''
    W = adjacency_matrix(A)
    D = sum_adjacency_matrix(W)

    Q = tau * (D - alpha * W) # the formula
    return np.linalg.inv(Q)

In [22]:
# Testing the functions

A = np.array([[1,2,3],[4,5,6],[7,8,9]])
W = adjacency_matrix(A)
D = sum_adjacency_matrix(W)
sigma = compute_sigma(A, 0.99, 1)

print(f'W: {W}')
print(f'D: {D}')
print(f'Sigma: {sigma}')

W: [[0 1 0 1 0 0 0 0 0]
 [1 0 1 0 1 0 0 0 0]
 [0 1 0 0 0 1 0 0 0]
 [1 0 0 0 1 0 1 0 0]
 [0 1 0 1 0 1 0 1 0]
 [0 0 1 0 1 0 0 0 1]
 [0 0 0 1 0 0 0 1 0]
 [0 0 0 0 1 0 1 0 1]
 [0 0 0 0 0 1 0 1 0]]
D: [[2 0 0 0 0 0 0 0 0]
 [0 3 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 3 0]
 [0 0 0 0 0 0 0 0 2]]
Sigma: [[4.72557687 4.26825946 4.10427136 4.26825946 4.10427136 4.02319782
  4.10427136 4.02319782 3.98296585]
 [4.26825946 4.51847503 4.26825946 4.10427136 4.14572864 4.10427136
  4.02319782 4.02340102 4.02319782]
 [4.10427136 4.26825946 4.72557687 4.02319782 4.10427136 4.26825946
  3.98296585 4.02319782 4.10427136]
 [4.26825946 4.10427136 4.02319782 4.51847503 4.14572864 4.02340102
  4.26825946 4.10427136 4.02319782]
 [4.10427136 4.14572864 4.10427136 4.14572864 4.35427136 4.14572864
  4.10427136 4.14572864 4.10427136]
 [4.02319782 4.10427136 4.26825946 4.02340102 4.14572864 4.51847503
  4.02319782 4.1042

In [23]:
# With the full 10x10 grid:

A = np.zeros((10,10), dtype=int)
W = adjacency_matrix(A)
D = sum_adjacency_matrix(W)
sigma = compute_sigma(A, 0.99, 1)

print(f'W: {W}')
print(f'D: {D}')
print(f'Sigma: {sigma}')

W: [[0 1 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 1 0 1]
 [0 0 0 ... 0 1 0]]
D: [[2 0 0 ... 0 0 0]
 [0 3 0 ... 0 0 0]
 [0 0 3 ... 0 0 0]
 ...
 [0 0 0 ... 3 0 0]
 [0 0 0 ... 0 3 0]
 [0 0 0 ... 0 0 2]]
Sigma: [[1.44637106 0.95593036 0.68112832 ... 0.14572908 0.1416529  0.14023637]
 [0.95593036 1.16191315 0.77788798 ... 0.14658889 0.14288171 0.1416529 ]
 [0.68112832 0.77788798 1.04330611 ... 0.14958705 0.14658889 0.14572908]
 ...
 [0.14572908 0.14658889 0.14958705 ... 1.04330611 0.77788798 0.68112832]
 [0.1416529  0.14288171 0.14658889 ... 0.77788798 1.16191315 0.95593036]
 [0.14023637 0.1416529  0.14572908 ... 0.68112832 0.95593036 1.44637106]]
